CREATE TABLE cms_snippets (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(191) NOT NULL,
    html       TEXT NOT NULL DEFAULT (''),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
